### PR TITLE
Remove vaex Notebook

### PR DESCRIPTION
**Pull request by martinRenou**
This Notebook relies on a huge dataset that we cannot put on the repository, so I thought it might be a good idea to remove it. Any thoughts?

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Makes sense, we could also use the remote dataframe API, it would require an internet connection though. Let me know if you're interested.

**Comment by martinRenou** [comment]
We are trying to clean up the Notebooks directory a bit, so if we go using the remote dataframe API thing we might want to put the vaex Notebook under the `extra_examples` directory? https://github.com/jupyter-widgets/tutorial/tree/master/notebooks/extra_examples

**Comment by mwcraig** [comment]
> We are trying to clean up the Notebooks directory a bit, so if we go using the remote dataframe API thing we might want to put the vaex Notebook under the extra_examples directory?

I think it would be good to include it in the extra_examples directory. It is an impressive package that widget folks should be aware exists, and I see the "extras" folder as that.

**Comment by mwcraig** [comment]
@martinRenou -- what do we need to do to wrap this up?

**Comment by martinRenou** [comment]
Maybe we can move this Notebook in the extra_examples repository and add a comment showing where to download the dataset?

**Comment by mwcraig** [comment]
OK, I'll open a PR to do that later today.

**Comment by martinRenou** [comment]
Done in #90

**Pull request closed without merging**
