### PR TITLE
Update dependencies and README

### PR DESCRIPTION
**Pull request by mwcraig**
This PR updates the dependencies to reflect what is used in the notebooks and adds a tool that scrapes the notebooks and python files to determine the dependencies. 

ping @jasongrout @maartenbreddels @SylvainCorlay 

*Note:* I'm thinking about breaking out the dependency checker into a separate package (combined with some utilities for generating notebook stubs from a table of contents or vice versa).

Even if it stays here it means not having to manually check each notebook for dependencies.

### CODE REVIEW

**Comment by mwcraig** [comment]
Question: does pip install still need the separate step of enabling nbextensions?

**Comment by mwcraig** [comment]
Question: Are we aiming for jupyter or jlab? (for users I mean)

**Comment by jasongrout** [comment]
> Question: does pip install still need the separate step of enabling nbextensions?

No, not with notebook 5.5

**Comment by jasongrout** [comment]
> Question: Are we aiming for jupyter or jlab? (for users I mean)

There still are some things with the output widget that don't quite work with JupyterLab. I hope to be able to fix those before scipy. What do you think? I'm thinking the safe bet is no, not with lab. But if we get it working by scipy, perhaps we can update the instructions?

**Pull request merged**
